Repository be15-FreePath-DevPath/be15-2nd-FreePath-DevPath-BE, pull requests merged in 2025-04, with the labels that each got.

#3 feat: 유저 회원가입 기능 구현
  build.gradle
  src/main/java/com/freepath/devpath/command/controller/UserCommandController.java
  src/main/java/com/freepath/devpath/command/entity/User.java
  src/main/java/com/freepath/devpath/command/entity/UserRole.java
  src/main/java/com/freepath/devpath/command/repository/UserRepository.java
  src/main/java/com/freepath/devpath/command/service/UserCommandService.java
  src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
  src/main/java/com/freepath/devpath/common/dto/UserCreateRequest.java
  src/main/java/com/freepath/devpath/common/jwt/RestAccessDeniedHandler.java
  src/main/java/com/freepath/devpath/common/jwt/RestAuthenticationEntryPoint.java
  src/main/java/com/freepath/devpath/common/response/ApiResponse.java
  src/main/resources/application.yml
Labels: enhancement

#6 [fix #5] 유저 회원가입 DTO 수정
  src/main/java/com/freepath/devpath/user/command/dto/UserCreateRequest.java
Labels: fix

#11 feat: 회원 정보 수정, 삭제 기능 구현
  src/main/java/com/freepath/devpath/common/auth/controller/AuthController.java
  src/main/java/com/freepath/devpath/common/auth/dto/UserDeleteRequest.java
  src/main/java/com/freepath/devpath/common/auth/service/AuthService.java
  src/main/java/com/freepath/devpath/common/auth/service/CustomUserDetailsService.java
  src/main/java/com/freepath/devpath/common/config/RedisConfig.java
  src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
  src/main/java/com/freepath/devpath/common/jwt/JwtTokenProvider.java
  src/main/java/com/freepath/devpath/user/command/controller/UserCommandController.java
  src/main/java/com/freepath/devpath/user/command/dto/UserModifyRequest.java
  src/main/java/com/freepath/devpath/user/command/entity/User.java
  src/main/java/com/freepath/devpath/user/command/repository/UserRepository.java
  src/main/java/com/freepath/devpath/user/command/service/UserCommandService.java
  src/main/java/com/freepath/devpath/user/exception/UserException.java
  src/main/resources/application.yml
Labels: enhancement

#18 채팅방 기능 구현
  src/main/java/com/freepath/devpath/chattingroom/command/application/controller/ChattingRoomCommandController.java
  src/main/java/com/freepath/devpath/chattingroom/command/application/dto/request/ChattingRoomCreateRequest.java
  src/main/java/com/freepath/devpath/chattingroom/command/application/dto/response/ChattingRoomCommandResponse.java
  src/main/java/com/freepath/devpath/chattingroom/command/application/service/ChattingRoomCommandService.java
  src/main/java/com/freepath/devpath/chattingroom/command/domain/aggregate/ChattingJoin.java
  src/main/java/com/freepath/devpath/chattingroom/command/domain/aggregate/ChattingJoinId.java
  src/main/java/com/freepath/devpath/chattingroom/command/domain/aggregate/ChattingRole.java
  src/main/java/com/freepath/devpath/chattingroom/command/domain/aggregate/ChattingRoom.java
  src/main/java/com/freepath/devpath/chattingroom/command/domain/repository/ChattingJoinRepository.java
  src/main/java/com/freepath/devpath/chattingroom/command/domain/repository/ChattingRoomRepository.java
  src/main/java/com/freepath/devpath/chattingroom/query/controller/ChattingRoomQueryController.java
  src/main/java/com/freepath/devpath/chattingroom/query/dto/ChattingRoomDTO.java
  src/main/java/com/freepath/devpath/chattingroom/query/dto/ChattingRoomResponse.java
  src/main/java/com/freepath/devpath/chattingroom/query/mapper/ChattingRoomMapper.java
  src/main/java/com/freepath/devpath/chattingroom/query/service/ChattingRoomQueryService.java
  src/main/resources/mappers/com/devpath/chattingroom/query/mapper/chattingRoomMapper.xml
Labels: enhancement

#23 bug: delete user 시 발생하는 오류 수정
  src/main/java/com/freepath/devpath/common/auth/controller/AuthController.java
  src/main/java/com/freepath/devpath/common/auth/service/AuthService.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
Labels: bug

#31 feat: 면접 진행기능 구현
  build.gradle
  src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
  src/main/java/com/freepath/devpath/common/config/WebClientConfig.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
  src/main/java/com/freepath/devpath/interview/command/application/controller/InterviewCommandController.java
  src/main/java/com/freepath/devpath/interview/command/application/dto/request/InterviewAnswerCommandRequest.java
  src/main/java/com/freepath/devpath/interview/command/application/dto/request/InterviewRoomCommandRequest.java
  src/main/java/com/freepath/devpath/interview/command/application/dto/response/InterviewAnswerCommandResponse.java
  src/main/java/com/freepath/devpath/interview/command/application/dto/response/InterviewRoomCommandResponse.java
  src/main/java/com/freepath/devpath/interview/command/application/service/InterviewCommandService.java
  src/main/java/com/freepath/devpath/interview/command/domain/aggregate/Interview.java
  src/main/java/com/freepath/devpath/interview/command/domain/aggregate/InterviewRoom.java
  src/main/java/com/freepath/devpath/interview/command/domain/repository/InterviewRepository.java
  src/main/java/com/freepath/devpath/interview/command/domain/repository/InterviewRoomRepository.java
  src/main/java/com/freepath/devpath/interview/command/exception/InterviewAnswerEmptyException.java
  src/main/java/com/freepath/devpath/interview/command/exception/InterviewEvaluationCreationException.java
  src/main/java/com/freepath/devpath/interview/command/exception/InterviewIndexInvalidException.java
  src/main/java/com/freepath/devpath/interview/command/exception/InterviewQuestionCreationException.java
  src/main/java/com/freepath/devpath/interview/command/exception/InterviewRoomAccessException.java
  src/main/java/com/freepath/devpath/interview/command/exception/InterviewRoomCreationException.java
  src/main/java/com/freepath/devpath/interview/command/exception/InterviewRoomNotFoundException.java
  src/main/java/com/freepath/devpath/interview/command/infrastructure.gpt/GptService.java
  src/main/resources/application.yml
Labels: enhancement

#34 feat: 회원 이메일을 통해 로그인 아이디 찾기 기능 구현
  src/main/java/com/freepath/devpath/common/auth/controller/AuthController.java
  src/main/java/com/freepath/devpath/common/auth/service/AuthService.java
  src/main/java/com/freepath/devpath/common/auth/service/CustomUserDetailsService.java
  src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
  src/main/java/com/freepath/devpath/email/command/application/service/EmailService.java
  src/main/java/com/freepath/devpath/email/command/application/service/NewsService.java
  src/main/java/com/freepath/devpath/email/command/domain/domain/News.java
  src/main/java/com/freepath/devpath/user/command/controller/UserCommandController.java
  src/main/java/com/freepath/devpath/user/command/repository/UserCommandRepository.java
  src/main/java/com/freepath/devpath/user/command/service/UserCommandService.java
  src/main/java/com/freepath/devpath/user/query/controller/UserQueryController.java
  src/main/java/com/freepath/devpath/user/query/mapper/UserMapper.java
  src/main/java/com/freepath/devpath/user/query/service/UserQueryService.java
  src/main/resources/mappers/chatting/chattingRoomMapper.xml
  src/main/resources/mappers/user/UserMapper.xml
Labels: enhancement

#36 fix: user 관련 코드의 변수명 불일치, 코드 누락 수정
  src/main/java/com/freepath/devpath/email/command/application/service/EmailService.java
  src/main/java/com/freepath/devpath/email/command/application/service/NewsService.java
  src/main/resources/mappers/chatting/ChattingRoomMapper.xml
  src/main/resources/mappers/chatting/chattingRoomMapper.xml
Labels: bug

#38 fix: GptService 경로 수정
  src/main/java/com/freepath/devpath/interview/command/infrastructure/gpt/GptService.java
  src/main/java/com/freepath/devpath/interview/query/controller/InterviewQueryController.java
  src/main/java/com/freepath/devpath/interview/query/dto/InterviewRoomDto.java
  src/main/java/com/freepath/devpath/interview/query/mapper/InterviewMapper.java
  src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryService.java
  src/main/resources/mappers/interview/InterviewMapper.xml
Labels: bug

#42 Feature/cs quiz
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
  src/main/java/com/freepath/devpath/csquiz/command/application/controller/AdminCsQuizController.java
  src/main/java/com/freepath/devpath/csquiz/command/application/controller/UserCsQuizController.java
  src/main/java/com/freepath/devpath/csquiz/command/application/dto/CsQuizCreateRequest.java
  src/main/java/com/freepath/devpath/csquiz/command/application/dto/CsQuizOptionCreateRequest.java
  src/main/java/com/freepath/devpath/csquiz/command/application/dto/CsQuizOptionUpdateRequest.java
  src/main/java/com/freepath/devpath/csquiz/command/application/dto/CsQuizResultRequest.java
  src/main/java/com/freepath/devpath/csquiz/command/application/dto/CsQuizUpdateRequest.java
  src/main/java/com/freepath/devpath/csquiz/command/application/service/CsQuizResultService.java
  src/main/java/com/freepath/devpath/csquiz/command/application/service/CsQuizScheduler.java
  src/main/java/com/freepath/devpath/csquiz/command/application/service/CsQuizSchedulerService.java
  src/main/java/com/freepath/devpath/csquiz/command/application/service/CsQuizService.java
  src/main/java/com/freepath/devpath/csquiz/command/domain/aggregate/CsQuiz.java
  src/main/java/com/freepath/devpath/csquiz/command/domain/aggregate/CsQuizOption.java
  src/main/java/com/freepath/devpath/csquiz/command/domain/aggregate/CsQuizResult.java
  src/main/java/com/freepath/devpath/csquiz/command/domain/repository/CsQuizOptionRepository.java
  src/main/java/com/freepath/devpath/csquiz/command/domain/repository/CsQuizRepository.java
  src/main/java/com/freepath/devpath/csquiz/command/domain/repository/CsQuizResultRepository.java
  src/main/java/com/freepath/devpath/csquiz/exception/CsQuizNotFoundException.java
  src/main/java/com/freepath/devpath/csquiz/query/controller/CsQuizQueryController.java
  src/main/java/com/freepath/devpath/csquiz/query/dto/CsQuizDetailResultDTO.java
  src/main/java/com/freepath/devpath/csquiz/query/dto/CsQuizListResponse.java
  src/main/java/com/freepath/devpath/csquiz/query/dto/CsQuizOptionDTO.java
  src/main/java/com/freepath/devpath/csquiz/query/dto/CsQuizOptionResponse.java
  src/main/java/com/freepath/devpath/csquiz/query/dto/CsQuizPreviewDTO.java
  src/main/java/com/freepath/devpath/csquiz/query/dto/CsQuizResponse.java
  src/main/java/com/freepath/devpath/csquiz/query/dto/CsQuizSearchRequest.java
  src/main/java/com/freepath/devpath/csquiz/query/mapper/CsQuizQueryMapper.java
  src/main/java/com/freepath/devpath/csquiz/query/service/CsQuizQueryService.java
  src/main/resources/mappers/csquiz/query/CsQuizMapper.xml
Labels: enhancement

#45 feat: 게시물 조회, 카테고리 조회 기능 구현
  src/main/java/com/freepath/devpath/board/post/command/controller/PostCommandController.java
  src/main/java/com/freepath/devpath/board/post/command/service/PostCommandService.java
  src/main/java/com/freepath/devpath/board/post/query/controller/PostQueryController.java
  src/main/java/com/freepath/devpath/board/post/query/dto/request/PostSearchRequest.java
  src/main/java/com/freepath/devpath/board/post/query/dto/response/CategoryListResponse.java
  src/main/java/com/freepath/devpath/board/post/query/dto/response/CatetgoryDto.java
  src/main/java/com/freepath/devpath/board/post/query/dto/response/PostDetailDto.java
  src/main/java/com/freepath/devpath/board/post/query/dto/response/PostDetailResponse.java
  src/main/java/com/freepath/devpath/board/post/query/dto/response/PostDto.java
  src/main/java/com/freepath/devpath/board/post/query/dto/response/PostListResponse.java
  src/main/java/com/freepath/devpath/board/post/query/exception/NoSuchPostException.java
  src/main/java/com/freepath/devpath/board/post/query/mapper/PostMapper.java
  src/main/java/com/freepath/devpath/board/post/query/service/PostQueryService.java
  src/main/resources/mappers/board/postMapper.xml
Labels: enhancement

#60 feat: 게시물 투표 등록 기능 구현
  src/main/java/com/freepath/devpath/board/post/command/controller/PostCommandController.java
  src/main/java/com/freepath/devpath/board/post/command/dto/request/PostCreateRequest.java
  src/main/java/com/freepath/devpath/board/post/command/dto/request/PostUpdateRequest.java
  src/main/java/com/freepath/devpath/board/post/command/dto/response/PostCreateResponse.java
  src/main/java/com/freepath/devpath/board/post/command/service/AttachmentService.java
  src/main/java/com/freepath/devpath/board/post/command/service/PostCommandService.java
  src/main/java/com/freepath/devpath/board/vote/command/dto/request/VoteCreateRequest.java
  src/main/java/com/freepath/devpath/board/vote/command/entity/Vote.java
  src/main/java/com/freepath/devpath/board/vote/command/entity/VoteItem.java
  src/main/java/com/freepath/devpath/board/vote/command/repository/VoteItemRepository.java
  src/main/java/com/freepath/devpath/board/vote/command/repository/VoteRepository.java
  src/main/java/com/freepath/devpath/board/vote/command/service/VoteService.java
Labels: enhancement

#64 feat: 투표 참여 기능 구현
  src/main/java/com/freepath/devpath/board/vote/command/controller/VoteController.java
  src/main/java/com/freepath/devpath/board/vote/command/dto/request/VoteParticipateRequest.java
  src/main/java/com/freepath/devpath/board/vote/command/entity/VoteHistory.java
  src/main/java/com/freepath/devpath/board/vote/command/exception/VoteParticipateFailedException.java
  src/main/java/com/freepath/devpath/board/vote/command/repository/VoteHistoryRepository.java
  src/main/java/com/freepath/devpath/board/vote/command/service/VoteService.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
Labels: enhancement

#67 feat: 투표 종료 기능 구현
  src/main/java/com/freepath/devpath/board/vote/command/controller/VoteController.java
  src/main/java/com/freepath/devpath/board/vote/command/entity/Vote.java
  src/main/java/com/freepath/devpath/board/vote/command/exception/VoteEndFailedException.java
  src/main/java/com/freepath/devpath/board/vote/command/repository/VoteRepository.java
  src/main/java/com/freepath/devpath/board/vote/command/service/VoteService.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
Labels: enhancement

#76 feat: 면접 응답 정확도 및 품질 개선
  src/main/java/com/freepath/devpath/interview/command/infrastructure/gpt/GptService.java
Labels: enhancement

#78 feat: 게시물 검색 구현(게시물 내용 검색 부분 제외)
  src/main/java/com/freepath/devpath/board/post/query/controller/PostQueryController.java
  src/main/java/com/freepath/devpath/board/post/query/dto/request/PostSearchRequest.java
  src/main/java/com/freepath/devpath/board/post/query/dto/response/PostDto.java
  src/main/java/com/freepath/devpath/board/post/query/exception/InvalidDateIntervalException.java
  src/main/java/com/freepath/devpath/board/post/query/mapper/PostMapper.java
  src/main/java/com/freepath/devpath/board/post/query/service/PostQueryService.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
  src/main/resources/mappers/board/PostMapper.xml
Labels: enhancement

#79 채팅방 이름 기능 수정 및 구현
  src/main/java/com/freepath/devpath/chatting/command/application/controller/ChattingRoomCommandController.java
  src/main/java/com/freepath/devpath/chatting/command/application/controller/WaitingRoomCommandController.java
  src/main/java/com/freepath/devpath/chatting/command/application/dto/request/GroupChattingRoomCreateRequest.java
  src/main/java/com/freepath/devpath/chatting/command/application/dto/request/GroupChattingRoomUpdateRequest.java
  src/main/java/com/freepath/devpath/chatting/command/application/dto/request/WaitingRoomActionRequest.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/ChattingRoomCommandService.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/WaitingRoomCommandService.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
Labels: enhancement, fix

#86 Feature/interaction
  src/main/java/com/freepath/devpath/board/interaction/command/application/controller/BookmarkController.java
  src/main/java/com/freepath/devpath/board/interaction/command/application/controller/LikeController.java
  src/main/java/com/freepath/devpath/board/interaction/command/application/dto/BookmarkRequest.java
  src/main/java/com/freepath/devpath/board/interaction/command/application/dto/LikeRequest.java
  src/main/java/com/freepath/devpath/board/interaction/command/application/service/BookmarkService.java
  src/main/java/com/freepath/devpath/board/interaction/command/application/service/LikeService.java
  src/main/java/com/freepath/devpath/board/interaction/command/domain/aggregate/Bookmark.java
  src/main/java/com/freepath/devpath/board/interaction/command/domain/aggregate/Like.java
  src/main/java/com/freepath/devpath/board/interaction/command/domain/repository/BookmarkRepository.java
  src/main/java/com/freepath/devpath/board/interaction/command/domain/repository/LikeRepository.java
  src/main/java/com/freepath/devpath/board/interaction/exception/AlreadyBookmarkedException.java
  src/main/java/com/freepath/devpath/board/interaction/exception/AlreadyLikedException.java
  src/main/java/com/freepath/devpath/board/interaction/exception/BoardNotFoundException.java
  src/main/java/com/freepath/devpath/board/interaction/exception/BookmarkNotFoundException.java
  src/main/java/com/freepath/devpath/board/interaction/exception/CannotLikeBothException.java
  src/main/java/com/freepath/devpath/board/interaction/exception/CommentNotFoundException.java
  src/main/java/com/freepath/devpath/board/interaction/exception/InvalidLikeTargetException.java
  src/main/java/com/freepath/devpath/board/interaction/exception/LikeNotFoundException.java
  src/main/java/com/freepath/devpath/board/interaction/query/controller/BookmarkQueryController.java
  src/main/java/com/freepath/devpath/board/interaction/query/controller/LikeQueryController.java
  src/main/java/com/freepath/devpath/board/interaction/query/dto/BookmarkedBoardSearchRequest.java
  src/main/java/com/freepath/devpath/board/interaction/query/dto/LikedBoardSearchRequest.java
  src/main/java/com/freepath/devpath/board/interaction/query/mapper/BookmarkQueryMapper.java
  src/main/java/com/freepath/devpath/board/interaction/query/mapper/LikeQueryMapper.java
  src/main/java/com/freepath/devpath/board/interaction/query/service/BookmarkQueryService.java
  src/main/java/com/freepath/devpath/board/interaction/query/service/LikeQueryService.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
  src/main/java/com/freepath/devpath/csquiz/command/application/controller/AdminCsQuizController.java
  src/main/java/com/freepath/devpath/csquiz/command/application/controller/UserCsQuizController.java
  src/main/java/com/freepath/devpath/csquiz/command/application/dto/CsQuizResultRequest.java
  src/main/java/com/freepath/devpath/csquiz/command/application/service/CsQuizResultService.java
  src/main/java/com/freepath/devpath/csquiz/query/controller/CsQuizQueryController.java
  src/main/resources/mappers/board/BookmarkMapper.xml
  src/main/resources/mappers/board/LikeMapper.xml
Labels: enhancement

#87 feat: 게시글 내용 검색 필터(ElasticSearch 적용)
  build.gradle
  src/main/java/com/freepath/devpath/board/post/command/domain/Attachment.java
  src/main/java/com/freepath/devpath/board/post/command/domain/Board.java
  src/main/java/com/freepath/devpath/board/post/command/domain/BoardDocument.java
  src/main/java/com/freepath/devpath/board/post/command/repository/AttachmentRepository.java
  src/main/java/com/freepath/devpath/board/post/command/repository/PostElasticRepository.java
  src/main/java/com/freepath/devpath/board/post/command/repository/PostRepository.java
  src/main/java/com/freepath/devpath/board/post/command/service/AttachmentService.java
  src/main/java/com/freepath/devpath/board/post/command/service/PostCommandService.java
  src/main/java/com/freepath/devpath/board/post/query/controller/PostQueryController.java
  src/main/java/com/freepath/devpath/board/post/query/dto/request/PostContentSearchRequest.java
  src/main/java/com/freepath/devpath/board/post/query/mapper/PostMapper.java
  src/main/java/com/freepath/devpath/board/post/query/service/PostQueryService.java
  src/main/java/com/freepath/devpath/common/config/ElasticsearchConfig.java
  src/main/resources/application.yml
  src/main/resources/mappers/board/PostMapper.xml
Labels: enhancement

#89 fix: 패키지명 수정 리팩토링
  src/main/java/com/freepath/devpath/chatting/command/application/service/ChattingRoomCommandService.java
Labels: bug

#94 refactor: 게시글, 댓글 신고 로직 수정
  src/main/java/com/freepath/devpath/common/auth/service/CustomUserDetailsService.java
  src/main/java/com/freepath/devpath/report/domain/ReportCheck.java
  src/main/java/com/freepath/devpath/report/repository/ReportCheckRepository.java
  src/main/java/com/freepath/devpath/report/service/ReportService.java
Labels: fix

#96 feat: 관리자 신고 검토 내역 확인 및 처리 기능 구현
  src/main/java/com/freepath/devpath/board/comment/command/application/controller/CommentController.java
  src/main/java/com/freepath/devpath/board/comment/command/application/service/CommentCommandService.java
  src/main/java/com/freepath/devpath/board/comment/command/domain/domain/Comment.java
  src/main/java/com/freepath/devpath/board/comment/query/controller/CommentQueryController.java
  src/main/java/com/freepath/devpath/board/comment/query/dto/CommentDetailDto.java
  src/main/java/com/freepath/devpath/board/comment/query/exception/NoSuchCommentException.java
  src/main/java/com/freepath/devpath/board/comment/query/mapper/CommentMapper.java
  src/main/java/com/freepath/devpath/board/comment/query/service/CommentQueryService.java
  src/main/java/com/freepath/devpath/board/post/command/domain/Board.java
  src/main/java/com/freepath/devpath/board/post/command/service/PostCommandService.java
  src/main/java/com/freepath/devpath/board/post/query/mapper/PostMapper.java
  src/main/java/com/freepath/devpath/board/post/query/service/PostQueryService.java
  src/main/java/com/freepath/devpath/board/vote/command/entity/Vote.java
  src/main/java/com/freepath/devpath/board/vote/query/dto/response/VoteDetailDTO.java
  src/main/java/com/freepath/devpath/chatting/command/domain/aggregate/ChattingJoin.java
  src/main/java/com/freepath/devpath/common/auth/service/CustomUserDetailsService.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
  src/main/java/com/freepath/devpath/report/controller/ReportController.java
  src/main/java/com/freepath/devpath/report/domain/ReportCheck.java
  src/main/java/com/freepath/devpath/report/dto/request/ReportCheckRequest.java
  src/main/java/com/freepath/devpath/report/dto/response/ReportCheckDto.java
  src/main/java/com/freepath/devpath/report/dto/response/ReportCheckListResponse.java
  src/main/java/com/freepath/devpath/report/dto/response/ReportCheckWithIdDto.java
  src/main/java/com/freepath/devpath/report/exception/AlreadyCheckedReportException.java
  src/main/java/com/freepath/devpath/report/exception/NoSuchReportCheckException.java
  src/main/java/com/freepath/devpath/report/mapper/ReportMapper.java
  src/main/java/com/freepath/devpath/report/repository/ReportCheckRepository.java
  src/main/java/com/freepath/devpath/report/service/ReportService.java
  src/main/resources/mappers/board/PostMapper.xml
  src/main/resources/mappers/comments/comment.xml
  src/main/resources/mappers/report/ReportMapper.xml
Labels: enhancement

#100 feat: 일반 회원 가입 시, 아이디와 비밀번호에 제약 조건 추가
  src/main/java/com/freepath/devpath/common/auth/dto/LoginRequest.java
  src/main/java/com/freepath/devpath/user/command/dto/ChaengePasswordRequest.java
  src/main/java/com/freepath/devpath/user/command/dto/GoogleSignUpRequest.java
  src/main/java/com/freepath/devpath/user/command/dto/ResetPasswordRequest.java
  src/main/java/com/freepath/devpath/user/command/dto/UserCreateRequest.java
Labels: enhancement

#102 Feat/chatting
  src/main/java/com/freepath/devpath/chatting/command/application/controller/ChattingCommandController.java
  src/main/java/com/freepath/devpath/chatting/command/application/dto/response/ChattingDto.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/ChattingCommandService.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/ChattingJoinCommandService.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/ChattingRoomCommandService.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/WaitingRoomCommandService.java
  src/main/java/com/freepath/devpath/chatting/query/controller/ChattingQueryController.java
  src/main/java/com/freepath/devpath/chatting/query/controller/ChattingRoomQueryController.java
  src/main/java/com/freepath/devpath/chatting/query/dto/response/ChattingDTO.java
  src/main/java/com/freepath/devpath/chatting/query/dto/response/ChattingListResponse.java
  src/main/java/com/freepath/devpath/chatting/query/dto/response/ChattingRoomJoinUserDTO.java
  src/main/java/com/freepath/devpath/chatting/query/dto/response/ChattingRoomJoinUsersResponse.java
  src/main/java/com/freepath/devpath/chatting/query/mapper/ChattingMapper.java
  src/main/java/com/freepath/devpath/chatting/query/mapper/ChattingRoomMapper.java
  src/main/java/com/freepath/devpath/chatting/query/service/ChattingQueryService.java
  src/main/java/com/freepath/devpath/chatting/query/service/ChattingRoomQueryService.java
  src/main/java/com/freepath/devpath/common/jwt/StompAuthChannelInterceptor.java
  src/main/resources/mappers/chatting/ChattingMapper.xml
  src/main/resources/mappers/chatting/ChattingRoomMapper.xml
Labels: enhancement, fix

#107 feat: 탈퇴한 유저의 loginId 재사용 가능, auth와 user 컨텍스트의 컨트롤러에 @Tag, @Operation 추가
  src/main/java/com/freepath/devpath/common/auth/controller/AuthController.java
  src/main/java/com/freepath/devpath/common/auth/service/AuthService.java
  src/main/java/com/freepath/devpath/user/command/controller/UserCommandController.java
  src/main/java/com/freepath/devpath/user/command/repository/UserCommandRepository.java
  src/main/java/com/freepath/devpath/user/command/service/UserCommandService.java
  src/main/java/com/freepath/devpath/user/query/controller/MyPageController.java
  src/main/java/com/freepath/devpath/user/query/controller/UserQueryController.java
Labels: enhancement

#112 feat: 자신의 신고된 게시물 조회 기능 구현
  src/main/java/com/freepath/devpath/board/post/command/controller/PostCommandController.java
  src/main/java/com/freepath/devpath/board/post/command/service/PostCommandService.java
  src/main/java/com/freepath/devpath/board/post/query/controller/PostQueryController.java
  src/main/java/com/freepath/devpath/board/post/query/mapper/PostMapper.java
  src/main/java/com/freepath/devpath/board/post/query/service/PostQueryService.java
  src/main/java/com/freepath/devpath/common/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
  src/main/resources/mappers/board/PostMapper.xml
Labels: enhancement

#114 feat: 투표 컨택스트 Swagger 문서화 적용
  src/main/java/com/freepath/devpath/board/vote/command/controller/VoteCommandController.java
  src/main/java/com/freepath/devpath/board/vote/query/controller/VoteQueryController.java
Labels: enhancement

#116 feat: 유저 신고 컨택스트 Swagger 문서화 적용
  src/main/java/com/freepath/devpath/report/controller/ReportController.java
Labels: documentation

#117 swagger어노테이션 입력 및 mongodb 연결
  build.gradle
  src/main/java/com/freepath/devpath/chatting/command/application/controller/ChattingCommandController.java
  src/main/java/com/freepath/devpath/chatting/command/application/controller/ChattingRoomCommandController.java
  src/main/java/com/freepath/devpath/chatting/command/application/controller/UserBlockCommandController.java
  src/main/java/com/freepath/devpath/chatting/command/application/controller/WaitingRoomCommandController.java
  src/main/java/com/freepath/devpath/chatting/command/application/dto/request/ChattingRequest.java
  src/main/java/com/freepath/devpath/chatting/command/application/dto/response/ChattingListResponse.java
  src/main/java/com/freepath/devpath/chatting/command/application/dto/response/ChattingResponse.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/ChattingCommandService.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/ChattingJoinCommandService.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/ChattingRoomCommandService.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/UserBlockCommandService.java
  src/main/java/com/freepath/devpath/chatting/command/application/service/WaitingRoomCommandService.java
  src/main/java/com/freepath/devpath/chatting/command/domain/aggregate/ChattingRole.java
  src/main/java/com/freepath/devpath/chatting/command/domain/jpa/aggregate/ChattingJoin.java
  src/main/java/com/freepath/devpath/chatting/command/domain/jpa/aggregate/ChattingJoinId.java
  src/main/java/com/freepath/devpath/chatting/command/domain/jpa/aggregate/ChattingRole.java
  src/main/java/com/freepath/devpath/chatting/command/domain/jpa/aggregate/ChattingRoom.java
  src/main/java/com/freepath/devpath/chatting/command/domain/jpa/aggregate/UserBlock.java
  src/main/java/com/freepath/devpath/chatting/command/domain/jpa/repository/ChattingJoinRepository.java
  src/main/java/com/freepath/devpath/chatting/command/domain/jpa/repository/ChattingRoomRepository.java
  src/main/java/com/freepath/devpath/chatting/command/domain/jpa/repository/UserBlockRepository.java
  src/main/java/com/freepath/devpath/chatting/command/domain/mongo/aggregate/Chatting.java
  src/main/java/com/freepath/devpath/chatting/command/domain/mongo/repository/ChattingRepository.java
  src/main/java/com/freepath/devpath/chatting/command/domain/repository/ChattingRepository.java
  src/main/java/com/freepath/devpath/chatting/query/controller/ChattingQueryController.java
  src/main/java/com/freepath/devpath/chatting/query/controller/ChattingRoomQueryController.java
  src/main/java/com/freepath/devpath/chatting/query/controller/UserBlockQueryController.java
  src/main/java/com/freepath/devpath/chatting/query/dto/response/UserBlockDTO.java
  src/main/java/com/freepath/devpath/chatting/query/dto/response/UserBlockResponse.java
  src/main/java/com/freepath/devpath/chatting/query/mapper/UserBlockMapper.java
  src/main/java/com/freepath/devpath/chatting/query/service/ChattingQueryService.java
  src/main/java/com/freepath/devpath/chatting/query/service/ChattingRoomQueryService.java
  src/main/java/com/freepath/devpath/chatting/query/service/UserBlockQueryService.java
  src/main/java/com/freepath/devpath/user/command/repository/UserCommandRepository.java
  src/main/resources/application.yml
  src/main/resources/mappers/chatting/UserBlockMapper.xml
Labels: enhancement, fix

#120 feat: 개발자 성향 테스트 저장 기능 구현
  src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
  src/main/java/com/freepath/devpath/user/command/controller/UserCommandController.java
  src/main/java/com/freepath/devpath/user/command/dto/SaveDevMbti.java
  src/main/java/com/freepath/devpath/user/command/entity/User.java
  src/main/java/com/freepath/devpath/user/command/service/UserCommandService.java
Labels: enhancement

#126 feat: 투표 조회 시 예외 처리 로직 추가
  src/main/java/com/freepath/devpath/board/post/query/mapper/PostMapper.java
  src/main/java/com/freepath/devpath/board/vote/query/controller/VoteQueryController.java
  src/main/java/com/freepath/devpath/board/vote/query/service/VoteQueryService.java
  src/main/resources/mappers/board/PostMapper.xml
Labels: enhancement

#134 feat: 유저 일반 기능 security filter 설정 변경
  src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
Labels: enhancement

#136 Feature/interaction
  src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
Labels: fix

#167 feat: 게시글 등록 테스트 코드 작성
  devpath/src/main/java/com/freepath/devpath/board/post/command/dto/request/PostCreateRequest.java
  devpath/src/main/java/com/freepath/devpath/board/post/command/dto/request/PostUpdateRequest.java
  devpath/src/main/java/com/freepath/devpath/board/post/command/dto/response/PostCreateResponse.java
  devpath/src/main/java/com/freepath/devpath/board/vote/command/repository/VoteItemRepository.java
  devpath/src/main/java/com/freepath/devpath/board/vote/command/repository/VoteRepository.java
  devpath/src/test/java/com/freepath/devpath/board/post/command/controller/PostCommandControllerTest.java
  devpath/src/test/java/com/freepath/devpath/board/post/command/service/PostCommandServiceIntegrationTest.java
  devpath/src/test/java/com/freepath/devpath/board/post/command/service/PostCommandServiceTest.java
Labels: enhancement
